#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# FILE: TimeSeries_Plot_Generator.R
# AUTHORS: Christopher Felt ERDC-CRREL-NH
# DATE CREATED: 25 July 2020
# Version: 0.01
#
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# PURPOSE
# =======
#
# Generates custom plots tailored for u*, saltation count, total dust 
# conc., dust conc. at PM 1, 2.5, and 10, and vertical dust flux 
# (which includes PM 1, 2.5, and 10 in the same plot). Change which 
# plots are generated by specifying T/F for each graph variable in
# the hard-coded parameters section below.
# 
# 
# ASSUMPTIONS
# =======
#
# Plots require data to be in a format conistent with Nancy Parker's
# moving average u* processor script.
# Some axis limits and breaks may require customization depending on
# the range of input values.
# 
#

### Fix "Error in file(out, "wt") : cannot open the connection" error
tempdir()
# [1] "C:\Users\XYZ~1\AppData\Local\Temp\Rtmp86bEoJ\Rtxt32dcef24de2"
dir.create(tempdir())


#----------------------------------------------------------------------
# Load required libraries.
#----------------------------------------------------------------------

library(ggplot2)
library(lubridate)          # date time manipulation library
library(dplyr)              # data manipulation tools 
library(scales)
library(ggpmisc)
library(Rmisc)
library(stringr)
library(gridExtra)
library(grid)
library(patchwork) # To display 2 charts together
library(hrbrthemes)
library(forcats)
library(reshape2) # melt() function
library(tidyverse) # nest() function

library(ggforce) # facet_wrap_paginate() function
library(egg) # align plots such that width is consistent 

#----------------------------------------------------------------------
# Set hard-coded parameters.
#----------------------------------------------------------------------

# I/O directories
oDir  <- '~/DUST/Test/Output'
iDir  <- '~/DUST/Nancy Processed/2017'
iDir2 <- '~/DUST/Nancy Processed/1 min 2017'
# iDir  <- '~/DUST/Test/Output/saltation'

# Use Dir2 files for 1 1min timestamps?
iDir2On <- T

# Specify graphs to generate
# u* regress
uStar_regress <- T

# temperature
temperature <- T

# Saltation count
sensit_total <- F

# Total dust concentration
dust_conc_total <- T

# UB graphs
UB_1 <- F
UB_2.5 <- F
UB_10 <- F

# Dust flux plot
PM_1_2.5_10 <- F

# Filter
filterPM10 <- T

# Bin u*
uStarBin <- T

# histograms
# uStarBin must also be TRUE to generate histograms
histUStar <- F

# Generate csv of u* and us* data
# iDir2On AND Bin u* MUST be also TRUE
uStar_and_uSStar_csv <- F

# Generate csv of u* data
uStar_csv <- F

# Function to specify exponential tick mark labels for ggplot
# SOURCE: https://stackoverflow.com/questions/34533472/insert-blanks-into-a-vector-for-e-g-minor-tick-labels-in-r/34533473#34533473
every_nth <- function(x, nth, empty = TRUE, inverse = FALSE) 
{
  if (!inverse) {
    if(empty) {
      x[1:nth == 1] <- ""
      x
    } else {
      x[1:nth != 1]
    }
  } else {
    if(empty) {
      x[1:nth != 1] <- ""
      x
    } else {
      x[1:nth == 1]
    }
  }
}


#----------------------------------------------------------------------
# Process data files.
#----------------------------------------------------------------------

# Import .csv files from the input directory
fileList <- list.files(iDir, pattern="*.csv")
fileList2 <- list.files(iDir, pattern="*.txt")
fileList3 <- list.files(iDir2, pattern="*.csv")

# Generate plot names from fileList
removeTail <- function(x, sep = "_", del = 3){
  sapply(strsplit(x, split = sep, fixed = TRUE),
         function(xray) paste(head(xray, -del), collapse = sep))
} # selects head of string based on "_" seperator
removeHead <- function(y, sep = "_", del = 3){
  sapply(strsplit(y, split = sep, fixed = TRUE),
         function(yankee) paste(tail(yankee, del), collapse = sep))
} # selects tail end of string based on "_" separator

# Select resolution
plotName <- removeTail(fileList, sep = '_', del = 1)
plotName <- removeHead(plotName, sep = '_', del = 3)
# Select date and site info
plotTitle <- removeTail(fileList, sep = '_', del = 9)
# combine plotTitle + plotName
plotName <- paste0(plotTitle, "_", plotName)


# loop through each file and generate graphs
for(i in 1:length(fileList)){
  
  # announce progress
  print(paste0("Generating plots for file ", fileList[i], " and ", fileList2[i], " ..."))
  
  # File to read in
  processFile <- paste0(iDir, "/", fileList[i])
  processFile2 <- paste0(iDir, "/", fileList2[i])
  if(iDir2On == T){
    processFile3 <- paste0(iDir2, "/", fileList3[i])}
  
  # Read table. Detect all columns that contain data.
  process_head <- read.table(processFile, header = FALSE, sep = ",", 
                            col.names = paste0("V", seq_len(max(count.fields(processFile, sep = ',')))), fill = TRUE)
  process_head <- process_head[1,] # Select header column only 
  process_head[] <- lapply(process_head, as.character)
  
  # read from processFile2
  process_head2 <- read.table(processFile2, header = FALSE, sep = "\t", 
                             col.names = paste0("V", seq_len(max(count.fields(processFile2, sep = '\t')))), fill = TRUE)
  process_head2 <- process_head2[1,] # Select header column only 
  process_head2[] <- lapply(process_head2, as.character)
  
  # read from processFile3
  if(iDir2On == T){
    process_head3 <- read.table(processFile3, header = FALSE, sep = ",", 
                                              col.names = paste0("V", seq_len(max(count.fields(processFile3, sep = ',')))), fill = TRUE)
    process_head3 <- process_head3[1,] # Select header column only 
    process_head3[] <- lapply(process_head3, as.character)}
  
  # Select data only
  process <- read.table(processFile, header = TRUE, sep = ",", 
                        col.names = paste0("V", seq_len(max(count.fields(processFile, sep = ',')))), fill = TRUE)
  
  process2 <- read.table(processFile2, header = TRUE, sep = "\t", 
                        col.names = paste0("V", seq_len(max(count.fields(processFile2, sep = '\t')))), fill = TRUE)
  
  if(iDir2On == T){
    process3 <- read.table(processFile3, header = TRUE, sep = ",", 
                                          col.names = paste0("V", seq_len(max(count.fields(processFile3, sep = ',')))), fill = TRUE)}
  
  # Make df numeric
  process_mutate <- mutate_all(process, function(makeNum) as.numeric(as.character(makeNum)))
  
  process_mutate2 <- mutate_all(process2, function(makeNum) as.numeric(as.character(makeNum)))
  
  # Create new df with numeric df
  process_master <- process_mutate
  process_master2 <- process_mutate2
  
  # Insert timestamps as POSIXct class in column 1
  process_master[,1] <- as.POSIXct(process[,1], format="%Y-%m-%d %H:%M:%S", tz = "GMT")
  
  # repeat for processFile3
  if(iDir2On == T){
    process_master3 <- process3
    process_master3[,1] <- as.POSIXct(process3[,1], format="%Y-%m-%d %H:%M:%S", tz = "GMT")}
  
  process_master[is.na(process_master)] <- 0
  process_master2[is.na(process_master2)] <- 0
  
  # select time range in process_master2 identical to process_master
  if(iDir2On == T){
    process_master2[,1] <- as.POSIXct(process2[,1], format="%Y-%m-%d %H:%M:%S", tz = "GMT", origin = '1970-01-01')
    process_master2[,1] <- process_master3[,1]
    process_master2 <- process_master2[which(process_master2[,1] == process_master[1,1]):which(process_master2[,1] == process_master[nrow(process_master),1]),]
    }
  
  # Replace OPS heights 1.5m -> 1.25m; 3.0m -> 2.5m
  process_head <- data.frame(lapply(process_head, function(height15) {gsub("1.5m", "1.25m", height15)}), stringsAsFactors = FALSE)
  process_head <- data.frame(lapply(process_head, function(height30) {gsub("3.0m", "2.5m", height30)}), stringsAsFactors = FALSE)
  
  #---------------------
  # apply filter if applicable
  #---------------------
  if(filterPM10 == TRUE){
    
    # Replace negative dust flux values with 0
    temp_flux <- process_master[,74:85]
    temp_flux[temp_flux < 0] <- 0
    process_master[,74:85] <- temp_flux
    
    # Check for negative values in dust flux columns
    if(length(which(process_master[,74:85] < 0)) != 0){print("Warning! Negative values exist in Dust Flux columns!!")}
    
    # create new df with PM10 column
    pm10 <- data.frame(process_master$V85)
    
    
    # replace all values that exceed 2sd of the mean with 0s
    pm10_filt <- apply(pm10, 2, function(x) ifelse((x > (mean(pm10[,1]) + 2*sd(pm10[,1]))), 0, x))
    test <- pm10_filt
    pm10_filt2 <- apply(pm10, 2, function(x) ifelse((x < (mean(pm10[,1]) - 2*sd(pm10[,1]))), 0, x))
    
    # check for errors in filter
    print(paste0("Issues with filtering. If FALSE, no issues. x > sd*2: ",identical(pm10, pm10_filt), 
                 ". x < sd*2: ", identical(pm10, pm10_filt2), ". pm10_filt != pm10_filt2: ", identical(pm10_filt, pm10_filt2), "."))
    
    # remove all rows that were filtered in all dust flux columns
    print(process_master[which(pm10 != pm10_filt),74:85])
    process_master[which(pm10 != pm10_filt),74:85] <- 0
    process_master[which(pm10 != pm10_filt),86:109] <- 0 # apply to _filt columns
    print(process_master[which(pm10 != pm10_filt2),74:85]) 
    process_master[which(pm10 != pm10_filt2),74:85] <- 0
    process_master[which(pm10 != pm10_filt2),86:109] <- 0 # apply to _filt columns
    
    # remove all rows that were filtered in us* flux columns
    if(iDir2On == T){
      # list all columns in process_master2 to keep
      process_master2_filt <- c(14,15,19,20,24,25)
      process_master2[which(pm10 != pm10_filt),process_master2_filt] <- 0
      process_master2[which(pm10 != pm10_filt2),process_master2_filt] <- 0
    }
 
    
    # copy filtered values into process_master
    # process_master$V83 <- pm10_filt
    
    # test if dfs are identical all.equal(test, pm10_filt) <<<<<< more details  identical(test, pm10_filt) <<<<<<<< less details
    # test <- apply(process_master$V83, 2, sd, na.rm = TRUE)
    # test2 <- mean(process_master$V83)
    
    # test3 <- data.frame(process_master$V83[abs(process_master$V83 - mean(process_master$V83)) < 2*sd(process_master$V83)])
    # test3 <- data.frame(process_master$V83)
    
    # test4 <- data.frame(apply(test3, 2, function(x) ifelse((x > (mean(process_master$V83) + 2*sd(process_master$V83))), 0, x)))
    
    # test5 <- cbind(test4,test3)
    # test5$diff <- test5[,1] - test5[,2]
  }
  
  
  #---------------------
  # Bin u*
  #---------------------
  if(uStarBin == TRUE){
    
    # generate bin labels and assign a u* bin to each row in process_master
    process_master$uStarBin <- as.character(cut(process_master$V70, breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00), 
                                                labels=c("u* [0, 0.1]","u* (0.1, 0.2]","u* (0.2, 0.3]","u* (0.3, 0.4]","u* (0.4, 0.5]","u* (0.5, 0.6]",
                                                         "u* (0.6, 0.7]","u* (0.7, 0.8]","u* (0.8, 0.9]","u* (0.9, 1.0]")))
    
    # generate bin labels and assign a us* bin to each row in process_master
    process_master$usStarBinMD <- as.character(cut(process_master$V65, breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00), 
                                                   labels=c("us* [0, 0.1]","us* (0.1, 0.2]","us* (0.2, 0.3]","us* (0.3, 0.4]","us* (0.4, 0.5]","us* (0.5, 0.6]",
                                                            "us* (0.6, 0.7]","us* (0.7, 0.8]","us* (0.8, 0.9]","us* (0.9, 1.0]")))
    
    process_master$usStarBinMN <- as.character(cut(process_master$V66, breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00), 
                                                    labels=c("us* [0, 0.1]","us* (0.1, 0.2]","us* (0.2, 0.3]","us* (0.3, 0.4]","us* (0.4, 0.5]","us* (0.5, 0.6]",
                                                             "us* (0.6, 0.7]","us* (0.7, 0.8]","us* (0.8, 0.9]","us* (0.9, 1.0]")))
    
    
    if(iDir2On == TRUE){
      process_master2$usStarBinMD <- as.character(cut(process_master2$V29, breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00), 
                                                  labels=c("us* [0, 0.1]","us* (0.1, 0.2]","us* (0.2, 0.3]","us* (0.3, 0.4]","us* (0.4, 0.5]","us* (0.5, 0.6]",
                                                          "us* (0.6, 0.7]","us* (0.7, 0.8]","us* (0.8, 0.9]","us* (0.9, 1.0]")))
      process_master2$usStarBinMN <- as.character(cut(process_master2$V30, breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1.00), 
                                                      labels=c("us* [0, 0.1]","us* (0.1, 0.2]","us* (0.2, 0.3]","us* (0.3, 0.4]","us* (0.4, 0.5]","us* (0.5, 0.6]",
                                                              "us* (0.6, 0.7]","us* (0.7, 0.8]","us* (0.8, 0.9]","us* (0.9, 1.0]")))}
    
    
    #  check max u* value
    print(paste0("Max u* value: ", max(process_master$V70)))
    
  }
  
  
  #---------------------
  # Create u*  csv
  #---------------------
  if(uStar_csv == TRUE){
    
    # add bin columns to headers
    process_head[,110] <- "ustar_bin"
    process_head[,111] <- "usStar_MD_bin"
    process_head[,112] <- "usStar_MN_bin"
    
    # posixCT shenanigens to maintain coherent timestamps
    process_head[,1] <- as.POSIXct(process_head[,1], format="%Y-%m-%d %H:%M:%S", tz = "GMT")
    names(process_head) <- names(process_master)
    gattai_kanzen <- rbind(process_head,process_master)
    gattai_kanzen[,1] <- as.character(gattai_kanzen[,1])
    gattai_kanzen[1,1] <- "TIMESTAMP"
    
    # write .csv file  
    write.table(gattai_kanzen, paste0(oDir,"/",plotTitle[i],"_uStar_and_usStar_filtered_and_binned.csv"), 
                col.names=FALSE, row.names = FALSE, sep = ",")
    
  }
  
  
  #---------------------
  # Create u* plus us* csv
  #---------------------
  if(uStar_and_uSStar_csv == TRUE){
    
    # list all columns in process_master2 to keep
    process_master2_keep <- c(29,30,14,15,19,20,24,25,32,33)
    process_master2_temp <- process_master2[,process_master2_keep] # select data
    
    # combine us* with other data
    gattai_process_master <- cbind(process_master, process_master2_temp)
    
    # add bin columns to headers
    process_head[,96] <- "ustar_bin"
    process_head2[,32] <- "us_star_MD_bin"
    process_head2[,33] <- "us_star_MN_bin"
    
    # combine headers
    process_head2_temp <- process_head2[,process_master2_keep]
    gattai_process_head <- cbind(process_head, process_head2_temp)
    
    # posixCT shenanigens to maintain coherent timestamps
    gattai_process_head[,1] <- as.POSIXct(gattai_process_head[,1], format="%Y-%m-%d %H:%M:%S", tz = "GMT")
    names(gattai_process_head) <- names(gattai_process_master)
    gattai_kanzen <- rbind(gattai_process_head,gattai_process_master)
    gattai_kanzen[,1] <- as.character(gattai_kanzen[,1])
    gattai_kanzen[1,1] <- "TIMESTAMP"
    
    # write .csv file  
    write.table(gattai_kanzen, paste0(oDir,"/",plotTitle[i],"_15min_mov_avg_and_uStar_and_1min_dust_conc_and_usStar.csv"), 
                col.names=FALSE, row.names = FALSE, sep = ",")
    
  }
  
  
  #---------------------
  # Histogram
  #---------------------
  if(histUStar == TRUE){
    
    # convert wide format table to long format
    process_master_long <- melt(process_master, direction = 'long', id.vars = c("V1","uStarBin"), 
                                measure.vars = c("V72","V73","V74","V75","V76","V77","V78","V79","V80","V81","V82","V83"))
    
    # remove all rows where value = 0 (accomplished separately in ggplot)
    process_master_long <- process_master_long[process_master_long$value != 0,]
    
    # change underlying factor level names of variable column in process_master_long
    levels(process_master_long$variable) <- c("PM_0.5", "PM_0.7", "PM_1", "PM_1.5", "PM_2", "PM_2.5", "PM_3", "PM_4", "PM_5", "PM_6", "PM_8", "PM_10")
    
    # plot histograms of each u*/particle size bin
    dust_plot <- ggplot(data=process_master_long[which(process_master_long$value > 0),], aes(value)) +
      # geom_bar(stat = "identity", position = "dodge")
      geom_histogram() +
      theme_bw() +
      theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()) +
      
      labs(x = "F",
           y = "count",
           title = paste0(plotTitle[i])) +
      
      # display histograms of all factors at once. drop=F forces the display of plots with no points
      facet_grid(variable~uStarBin, drop=F)
    
    ggsave(paste0(oDir, "/", plotName[i], "_hist",".png"), plot = dust_plot, width = 7, height= 10, dpi=150)
    
    # summ <- process_master_long %>% nest(data=-c(variable))
    # summ2 <- summ %>% nest(data=-c(uStarBin))
    
    # test <- process_master_long %>% 
    #  group_by(.dots=c("uStarBin", "variable")) 
    
  }
  
  
  
  #---------------------
  # u* + temperature @ 3.0m plot
  #---------------------
  if(uStar_regress == TRUE){
    
    # V42 = temp @ 3.0m
    cols <- c("Temp."="red","u"="blue")
    # Plot variables
    
    process_master$uSStar_MD <- process_master2$V29
    process_master$uSStar_MN <- process_master2$V30
    
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      # labs(x = "Time", sizeof = 10) +
      
      # set variable aesthetics
      geom_line( aes(y=V69, color = "blue"), size = 0.25, show.legend = TRUE) +
      geom_line( aes(y=uSStar_MD, color = "green"), size = 0.25, show.legend = TRUE) +
      # geom_line( aes(y=V42/(mean(process_master$V42)), color = "red"), size = 0.25, show.legend = TRUE) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = expression(atop(" ", paste('Friction velocity',' (m s'^'-1', ')'))), limits=c(0.0,1.2),breaks=seq(0.1,2.0,0.2),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(0,50,10))
                         ) +
      # scale_x_datetime(date_labels = "%H:%M", date_breaks = "1 hour") +
      
      
      theme( # axis.text.x = element_text(size = 10, #margin = unit(c(t = 2.5, r = 0, b = 0, l = 0), "mm"))
            #                             ),
            axis.title.x=element_blank(),
            axis.text.x=element_blank(),
            axis.ticks.x=element_blank(),
            axis.text.y.left = element_text( color="black", 
                                       size=10),
            axis.title.y.left = element_text(colour = "black"),
            axis.ticks.y.left = element_line(color = "black"),
            axis.text.y.right = element_text( color="white", 
                                     size=10),
            axis.title.y.right = element_text(colour = "white"),
            axis.ticks.y.right = element_line(color = "white"),
            
            # Blank white background in plot
            # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
            panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
            # legend.spacing.x = unit(0.15, 'cm'), #adjust space size along x axis in legend
            
            legend.text.align = 0, # force text justification in legend to LEFT
            
            legend.background = element_rect(fill=alpha('transparent', 0.0)),
            legend.key.height = unit(0.65, 'lines'), #adjust space size along y axis in legend
            legend.position = c(0.91, 0.96)
            
            # panel.grid.major = element_blank(), panel.grid.minor = element_blank() ## Gray background, no grid
            
            # axis.ticks.length=unit(-0.25, "cm"), axis.ticks.margin=unit(0.5, "cm") ## invert tick marks
            ) +
      
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
      
      # Reverse order of legend (difficult to change order of variables) and set title
      guides(color = guide_legend(title = "", reverse=T)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      scale_color_manual(labels = c(expression(u['*']), 'Temp.'), values = c("blue", "red")) +

      # Set variable text in legend and override color in aesthetics to default ggplot values
      # "breaks = " overrrides order of legend using color of each aesthetic...
      scale_color_manual(labels = c(expression(paste('us'['*'])), expression(paste('u'['*'])), '°C'), 
                         values = c("green", "blue", "red"), breaks = c("green", "blue", "red"))
      
      
      # ggtitle(plotTitle[i])
      
      
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_u_Star_and_u_s_Star_MD",".png"), plot = dust_plot, width = 6, height= 2.25, dpi=900) #use dpi=900 for photoshop composites
    
  }
  
  
  #---------------------
  # temperature @ 3.0m plot TEST
  #---------------------
  if(temperature == TRUE){
    
    # V42 = temp @ 3.0m
    cols <- c("Temp."="red","u"="blue")
    # Plot variables
    
    process_master$uSStar_MD <- process_master2$V29
    process_master$uSStar_MN <- process_master2$V30
    
    dust_plot_t = ggplot(process_master, aes(x=V1)) +
      
      # labs(x = "Time", sizeof = 10) +
      
      # set variable aesthetics
      # geom_line( aes(y=V69, color = "blue"), size = 0.25, show.legend = TRUE) +
      # geom_line( aes(y=uSStar_MD, color = "green"), size = 0.25, show.legend = TRUE) +
      geom_line( aes(y=V42, color = "red"), size = 0.25, show.legend = FALSE) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = expression(atop(" ", paste("Temperature (°C)"))), limits=c(20,50),breaks=seq(20,50,5),
      #                    sec.axis = sec_axis(~ . *1, breaks=seq(0,5,1))
                         ) +
      # scale_x_datetime(date_labels = "%H:%M", date_breaks = "1 hour") +
      
      
      theme( # axis.text.x = element_text(color="black",size = 10, #margin = unit(c(t = 2.5, r = 0, b = 0, l = 0), "mm"))
      # ),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y.left = element_text( color="black", 
                                         size=10),
        axis.title.y.left = element_text(colour = "black"),
        axis.ticks.y.left = element_line(color = "black"),
        # axis.text.y.right = element_text( color="white", 
        #                                 size=10),
        # axis.title.y.right = element_text(colour = "white"),
        # axis.ticks.y.right = element_line(color = "white"),
        # axis.ticks.x.bottom = element_line(colour = "black"),
      
      
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
        # legend.spacing.x = unit(0.15, 'cm'), #adjust space size along x axis in legend
      
        legend.text.align = 0, # force text justification in legend to LEFT
      
        legend.background = element_rect(fill=alpha('transparent', 0.0)),
        legend.key.height = unit(0.65, 'lines'), #adjust space size along y axis in legend
        legend.position = c(0.9, 0.26)
        
        # Blank white background in plot
        # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
        # panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        # panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
        # legend.spacing.x = unit(0.15, 'cm'), #adjust space size along x axis in legend
        
        # legend.text.align = 0, # force text justification in legend to LEFT
        
        # legend.background = element_rect(fill=alpha('transparent', 0.0)),
        # legend.key.height = unit(0.65, 'lines'), #adjust space size along y axis in legend
        # legend.position = c(0.9, 0.94),
        
        # panel.grid.major = element_blank(), panel.grid.minor = element_blank() ## Gray background, no grid
        
        # axis.ticks.length=unit(-0.25, "cm"), axis.ticks.margin=unit(0.5, "cm") ## invert tick marks
        
        # panel.background = element_rect(fill = "transparent", color = NA), # bg of the panel
        # plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
        # panel.grid.major = element_blank(), # get rid of major grid
        # panel.grid.minor = element_blank(), # get rid of minor grid
        
        # panel.border = element_blank(),
        # axis.line = element_blank()
        # legend.background = element_rect(fill = "transparent"), # get rid of legend bg
        # legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
      )
      
      # Remove default gray background in legend
      # theme(legend.key=element_blank()) +
      
      # Reverse order of legend (difficult to change order of variables) and set title
      # guides(color = guide_legend(title = "", reverse=T)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      # scale_color_manual(labels = c(expression(u['*']), 'Temp.'), values = c("blue", "red")) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      # "breaks = " overrrides order of legend using color of each aesthetic...
      # scale_color_manual(labels = c(expression(paste('us'['*'])), expression(paste('u'['*'])), '°C'), 
      #                    values = c("green", "blue", "red"), breaks = c("green", "blue", "red")) +
      
      
      # ggtitle("")
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_temperature",".png"), plot = dust_plot_t, width = 6, height= 2, dpi=900) #use dpi=900 for photoshop composites
    
  }
  
  #---------------------
  # Saltation count plot
  #---------------------
  if(sensit_total == TRUE){
    
    # Plot variables
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      
      geom_line( aes(y=V10), color = "black", size = 0.25) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = "saltation\ncounts", limits = c(0, 50), breaks=seq(0,50,by = 25),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), name = expression(paste('u'['*'],' [m s'^'-1', ']')), breaks=seq(10.0,1000000,1000000))) +
      
      
      theme( axis.text.x = element_text(size = 10, 
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      axis.text.y.right = element_text( color="white", 
                                        size=9),
      axis.title.y.right = element_text(colour = "white"),
      axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5) # black line border outline
      
      ) # +
      
      # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_sensit_total.png"), plot = dust_plot, width = 6, height= 2.0, dpi=900) 
    
  }
  
  #---------------------
  # Total dust conc. plot; 1.5m = green, 3.0m = orange
  #---------------------
  if(dust_conc_total == TRUE){
    
    yAxisBreaks <- c((1:9 %o% 10^(0:3)), 10000)
    
    # Plot variables
    dust_plot_dct = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      
      geom_line( aes(y=V29, color = "purple"), size = 0.25) +
      geom_line( aes(y=V52, color = "orange"), size = 0.25) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      # scale_y_continuous(name = expression(atop('Total dust conc.', paste('(µg m'^'-3', ')'))), limits=c(0,4000),breaks=seq(0,4000,1000),
                   #      sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(1,50,10))
      #              ) +
      
      scale_y_log10(breaks = yAxisBreaks, labels = every_nth(yAxisBreaks, 9, inverse=TRUE), limits = c(1,10000),
                                  name = expression(atop('Total dust conc.', paste('(µg m'^'-3', ')')))
                                 ) +
      
  
      theme( axis.text.x = element_text(size = 10, color="black",
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      # axis.text.y.right = element_text( color="white", 
      #                                   size=24),
      # axis.title.y.right = element_blank(),
      # axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
      
      
      legend.text.align = 0, # force text justification in legend to LEFT
      
      # legend.background = element_rect(fill=alpha('transparent', 0.4)),

      # legend.text.align = 0, # force text justification in legend to LEFT
      
      legend.background = element_rect(fill=alpha('transparent', 0.0)),
      legend.key.height = unit(0.65, 'lines'), #adjust space size along y axis in legend
      legend.position = c(0.91, 0.96)
      ) +
      
      scale_x_datetime(date_labels = "%H:%M", date_breaks = "1 hour") +
    
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
      
      # Set legend title
      guides(color = guide_legend(title = "", reverse=F)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      scale_color_manual(labels = c('1.25m','2.5m'), values = c("purple", "orange"))
    
    # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_dust_conc._total.png"), plot = dust_plot_dct, width = 6, height= 2.25, dpi=900) 
    
    # generate collated image of u*, T, and dust conc
    if(uStar_regress == T && temperature == T){
      ggsave(paste0(oDir, "/", plotName[i], "_paper.png"), plot = ggarrange(dust_plot_t,dust_plot,dust_plot_dct, ncol=1, heights=c(0.8,1,1)), 
             width=6,height=5,dpi=900)}
    
  }
  
  #---------------------
  # UB_1; 1.5m = green, 3.0m = orange
  #---------------------
  if(UB_1 == TRUE){
    
    # Plot variables
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      
      geom_line( aes(y=V32, color = "green"), size = 0.25) +
      geom_line( aes(y=V55, color = "orange"), size = 0.25) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = expression(atop('dust conc. PM 1', paste('[µg m'^'-3', ']'))), # limits = c(0, 3), breaks=seq(0,3,by = 1),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(1,1000000,1000000))) +
      
      
      theme( axis.text.x = element_text(size = 10, 
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      axis.text.y.right = element_text(color="white", 
                                        size=18),
      axis.title.y.right = element_blank(),
      axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
      
      legend.text.align = 0, # force text justification in legend to LEFT
      
      legend.background = element_rect(fill=alpha('transparent', 0.4)),
      legend.position = c(0.90, 0.5)
      ) +
    
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
      
      # Set legend title
      guides(color = guide_legend(title = "", reverse=F)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      scale_color_manual(labels = c('1.5m','3.0m'), values = c("green", "orange"))
    
    # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_UB_1_1.5m_and_3.0m.png"), plot = dust_plot, width = 6, height= 2.25, dpi=900) 
    
    
  }
  
  #---------------------
  # UB_2.5; 1.5m = green, 3.0m = orange
  #---------------------
  if(UB_2.5 == TRUE){
    
    # Plot variables
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      
      geom_line( aes(y=V35, color = "green"), size = 0.25) +
      geom_line( aes(y=V58, color = "orange"), size = 0.25) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = expression(atop('dust conc. PM 2.5', paste('[µg m'^'-3', ']'))),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(1,1000000,1000000))) +
      
      
      theme( axis.text.x = element_text(size = 10, 
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      axis.text.y.right = element_text(color="white", 
                                       size=18),
      axis.title.y.right = element_blank(),
      axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
      
      legend.text.align = 0, # force text justification in legend to LEFT
      
      legend.background = element_rect(fill=alpha('transparent', 0.4)),
      legend.position = c(0.90, 0.5)
      ) +
    
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
      
      # Set legend title
      guides(color = guide_legend(title = "", reverse=F)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      scale_color_manual(labels = c('1.5m','3.0m'), values = c("green", "orange"))
    
    # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_UB_2.5_1.5m_and_3.0m.png"), plot = dust_plot, width = 6, height= 2.25, dpi=900) 
    
  }
  
  #---------------------
  # UB_10; 1.5m = green, 3.0m = orange
  #---------------------
  if(UB_10 == TRUE){
    
    # Plot variables
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      
      geom_line( aes(y=V41, color = "green"), size = 0.25) +
      geom_line( aes(y=V64, color = "orange"), size = 0.25) +
      
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      scale_y_continuous(name = expression(atop('dust conc. PM 10', paste('[µg m'^'-3', ']'))),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(1,1000000,1000000))) +
      
      
      theme( axis.text.x = element_text(size = 10, 
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      axis.text.y.right = element_text(color="white", 
                                       size=18),
      axis.title.y.right = element_blank(),
      axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
      
      legend.text.align = 0, # force text justification in legend to LEFT
      
      legend.background = element_rect(fill=alpha('transparent', 0.4)),
      legend.position = c(0.90, 0.5)
      ) +
    
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
      
      # Set legend title
      guides(color = guide_legend(title = "", reverse=F)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      scale_color_manual(labels = c('1.5m','3.0m'), values = c("green", "orange"))
    
    # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_UB_10_1.5m_and_3.0m.png"), plot = dust_plot, width = 6, height= 2.25, dpi=900) 
    
  }
  
  #---------------------
  # PM_1_2.5_10; PM_1 = green, PM_2.5 = orange, PM_10 = blue
  #---------------------
  if(PM_1_2.5_10 == TRUE){
    
    yAxisBreaks <- c(0.001,(2:10 %o% 10^(-4:2)))
    
    
    
    # Plot variables
    dust_plot = ggplot(process_master, aes(x=V1)) +
      
      labs(x = "Time", sizeof = 10) +
      
      geom_line( aes(y=V83, color = "blue"), size = 0.25) +
      geom_line( aes(y=V77, color = "orange"), size = 0.25) +
      geom_line( aes(y=V74, color = "green"), size = 0.25) +
      
      # pseudo log scale
      scale_y_continuous(trans=scales::pseudo_log_trans(base = 10),
                         name = expression(atop('vertical dust flux', paste('[µg m'^'-2', ' sec'^'-1', ']'))),
                         sec.axis = sec_axis(~ . *mean(process_master$V42), breaks=seq(1,1000000,1000000))) +
      
      # scale_y_log10(breaks = yAxisBreaks, labels = every_nth(yAxisBreaks, 9, inverse=TRUE), limits = c(0.001,100),
      #               name = expression(atop('vertical dust flux', paste('[µg m'^'-2', ' sec'^'-1', ']')))
      #               ) +
      # subscript and supscript method: https://stackoverflow.com/questions/10628547/use-superscripts-in-r-axis-labels
      # scale_y_continuous(name = expression(atop('vertical dust flux', paste('[µg m'^'-2', ' sec'^'-1', ']'))),
      #                    sec.axis = sec_axis(~ . *mean(process_master$V42), name = "°C", breaks=seq(1,1000000,1000000))) +
      
      
      theme( axis.text.x = element_text(size = 10, 
      ),
      axis.text.y.left = element_text( color="black", 
                                       size=10),
      axis.title.y.left = element_text(colour = "black"),
      axis.ticks.y.left = element_line(color = "black"),
      
      axis.text.y.right = element_text(color="white", 
                                       size=32),
      axis.title.y.right = element_text(color="white", 
                                        size=15),
      axis.ticks.y.right = element_line(color = "white"),
      
      # Blank white background in plot
      # Various backgrounds source: https://felixfan.github.io/ggplot2-remove-grid-background-margin/
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA, size=0.5), # black line border outline
      
      legend.text.align = 0, # force text justification in legend to LEFT
      
      legend.background = element_rect(fill=alpha('transparent', 0.4)),
      legend.position = c(0.90, 0.5)
      ) +
      
      # guides(linetype=guide_legend(override.aes=list(colour = c("blue","black","purple")))) +
      
      # Remove default gray background in legend
      theme(legend.key=element_blank()) +
        
      # Set legend title
      guides(color = guide_legend(title = "", reverse=F)) +
      
      # Set variable text in legend and override color in aesthetics to default ggplot values
      # "breaks = " overrrides order of legend using color of each aesthetic...
      scale_color_manual(labels = c('PM 1', 'PM 2.5', 'PM 10'), values = c("green", "orange", "blue"), breaks = c("green", "orange", "blue"))
    
    # ggtitle(plotTitle[i])
    
    
    # Generate .png file of plot 
    ggsave(paste0(oDir, "/", plotName[i], "_PM_1_2.5_and_10.png"), plot = dust_plot, width = 6, height= 2.25, dpi=900) 
    
  }
  
  # announce progress
  print("Complete!")
  
}

# announce progress
print("Finished processing all files. Goodbye.")